# Generated by Django 5.0 on 2023-12-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nome_social', models.CharField(max_length=80)),
                ('cpf', models.IntegerField(unique=True)),
                ('data_de_nascimento', models.DateField()),
                ('estado', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
