# Generated by Django 5.0 on 2023-12-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
