# Generated by Django 5.0 on 2023-12-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_aluno_nome_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=88),
        ),
    ]
