# Generated by Django 4.2.7 on 2023-12-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_aluno_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
    ]
