# Generated by Django 5.0 on 2024-01-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_aluno_crupo_de_atendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='crupo_de_atendimento',
            new_name='grupo_de_atendimento',
        ),
        migrations.AddField(
            model_name='aluno',
            name='teve_covid_recentemente',
            field=models.BooleanField(null=True),
        ),
    ]
