# Generated by Django 5.0 on 2024-01-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_rename_crupo_de_atendimento_aluno_grupo_de_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='teve_covid_recentemente',
            field=models.BooleanField(),
        ),
    ]
