# Generated by Django 5.0 on 2024-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_alter_aluno_grupo_de_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='grupo_de_atendimento',
            field=models.CharField(choices=[('0', 'Escolha uma opção'), ('1', 'Pessoas acima de 75 anos'), ('2', 'Pessoas entre 60 a 74 anos'), ('3', 'Forças de Segurança e Salvamento'), ('4', 'Funcionário do Sistema de Privação de Liberdade'), ('5', 'Trabalhadores da Saúde'), ('6', 'Pessoas acima de 60 anos institucionalizadas'), ('7', 'Pessoas em Situação de Rua'), ('8', 'Trabalhadores da educação'), ('9', 'Caminhoneiro'), ('10', 'Trabalhadores Portuários'), ('11', 'Pessoas de 60 a 64 anos'), ('12', 'Pessoas de 65 a 69 anos'), ('13', 'Pessoas de 70 a 74 anos'), ('14', 'Pessoas de 75 a 79 anos'), ('15', 'Pessoas de 80 anos ou mais'), ('16', 'Síndrome de Down'), ('17', 'Marinha do Brasil - MB'), ('18', 'Exército Brasileiro - EB'), ('19', 'Força Aérea Brasileira - FAB'), ('20', 'Bombeiro Civil'), ('21', 'Bombeiro Militar'), ('22', 'Guarda Municipal'), ('23', 'Policial Rodoviário Federal'), ('24', 'Policial Civil'), ('25', 'Policial Federal'), ('26', 'Policial Militar'), ('27', 'Quilombola'), ('28', 'Povos indígenas em terras indígenas'), ('29', 'Ensino Básico'), ('30', 'Ensino Superior'), ('31', 'Auxiliar de Veterinário'), ('32', 'Biólogo'), ('33', 'Biomédico'), ('34', 'Cozinheiro e Auxiliares'), ('35', 'Cuidador de Idosos'), ('36', 'Doula/Parteira'), ('37', 'Enfermeiro(a)'), ('38', 'Farmacêutico'), ('39', 'Fisioterapeutas'), ('40', 'Fonoaudiólogo'), ('41', 'Funcionário do Sistema Funerário que tenham contato com cadáveres potencialmente contaminados'), ('42', 'Médico'), ('43', 'Médico Veterinário'), ('44', 'Motorista de Ambulância'), ('45', 'Nutricionista'), ('46', 'Odontologista'), ('47', 'Pessoal da Limpeza'), ('48', 'Profissionais de Educação Física'), ('49', 'Psicólogo'), ('50', 'Recepcionista'), ('51', 'Segurança'), ('52', 'Assistente Social'), ('53', 'Técnico de Enfermagem'), ('54', 'Técnico de Veterinário'), ('55', 'Terapeuta Ocupacional'), ('56', 'Outros'), ('57', 'Auxiliar de Enfermagem'), ('58', 'Técnico de Odontologia'), ('59', 'Estudante'), ('60', 'Aéreo'), ('61', 'Coletivo Rodoviário Passageiros Urbano e de Longo Curso'), ('62', 'Ferroviário'), ('63', 'Metroviário'), ('64', 'Aquaviário'), ('65', 'Pessoas com Deficiência Institucionalizadas'), ('66', 'Pessoas com Deficiências Permanente Grave'), ('67', 'População Privada de Liberdade'), ('68', 'Trabalhadores Industriais'), ('69', 'Pessoas ACAMADAS de 75 a 79'), ('70', 'Pessoas ACAMADAS de 80 anos ou mais')], max_length=100),
        ),
    ]
