# Generated by Django 5.0 on 2024-02-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_rename_nome_aluno_nome_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_cnes', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
