# Generated by Django 5.0 on 2024-02-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_estabelecimento_grupodeatendimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrupoDeAtendimento',
        ),
    ]
