# Generated by Django 5.0 on 2024-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_alter_agendamento_date_alter_agendamento_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='time',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='date',
            field=models.CharField(max_length=50, verbose_name='horário'),
        ),
    ]
