# Generated by Django 5.0 on 2024-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_aluno_agendamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='agendamentos',
            field=models.ManyToManyField(blank=True, default=None, to='coreapp.agendamento'),
        ),
    ]
