# Generated by Django 5.0 on 2024-03-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_agendamento_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='aluno',
        ),
    ]
