# Generated by Django 5.0 on 2024-03-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0029_remove_agendamento_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coreapp.aluno'),
        ),
    ]
