# Generated by Django 5.0 on 2024-03-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0030_agendamento_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreapp.aluno'),
        ),
    ]
